use Students;

/*PET TABLE*/
insert into pet values('Fluffy','Harold','Cat','f','1993-02-04',NULL),
    ('Claws','Gwen','Cat','m','1994-03-17',NULL),
    ('Buffy','Harold','Dog','f','1989-05-13',NULL),
    ('Fang','Benny','Dog','m','1989-05-13',NULL),
    ('Bowser','Diane','Dog','m','1990-08-27',NULL),
    ('Chirpy','Gwen','Bird','f','1998-09-11','1995-07-29'),
    ('Whistler','Gwen','Bird',NULL,'1997-12-09',NULL),
    ('Slim','Benny','Snake','m','1996-04-29',NULL);
select * from pet;

/*ACTOR TABLE*/
insert into actor_New values(1,'PENELOPE','GUINESS','2006-02-15 04:34:33'),
                        (2,'NICK','WAHLBERG','2006-02-15 04:34:33'),
                        (3,'ED','CHASE','2006-02-15 04:34:33'),
                        (4,'JENNIFER','DAVIS','2006-02-15 04:34:33'),
                        (5,'JOHNY','LOLLOBRIGIDA','2006-02-15 04:34:33'),
                        (6,'BETTE','NICHOLSON','2006-02-15 04:34:33'),
                        (7,'GRACE','MOSTEL','2006-02-15 04:34:33'),
                        (8,'MATTHEW','JOHANSON','2006-02-15 04:34:33'),
                        (9,'JOE','SWANK','2006-02-15 04:34:33'),
                        (10,'CHRISTIAN','GABLE','2006-02-15 04:34:33');
select * from actor_New;

/*FILM TABLE*/
insert into film_New values(1,'ACADEMY DINOSAUR','A Epic drama of a Feminist And a Mad Scientist who must Battel a Teacher in the candian Rocikes','2006',1,NULL,6,0.99,86,20.99,'PG',('Deleted Scenes'),' 2006-02-15 05:03:42'),
                        (2,'ACE GOLDFINGER','A Epic drama of a Feminist And a Mad Scientist who must Battel a Teacher in the candian Rocikes','2006',1,NULL,6,0.99,86,20.99,'PG',('Deleted Scenes'),' 2006-02-15 05:03:42'),
                        (3,'ADAPTATION HOLES','A Epic drama of a Feminist And a Mad Scientist who must Battel a Teacher in the candian Rocikes','2006',1,NULL,6,0.99,86,20.99,'PG',('Deleted Scenes'),' 2006-02-15 05:03:42'),
                        (4,'AFFAIR PREJUDICES','A Epic drama of a Feminist And a Mad Scientist who must Battel a Teacher in the candian Rocikes','2006',1,NULL,6,0.99,86,20.99,'PG',('Deleted Scenes'),' 2006-02-15 05:03:42'),
                        (5,'AFRICAN EGG','A Epic drama of a Feminist And a Mad Scientist who must Battel a Teacher in the candian Rocikes','2006',1,NULL,6,0.99,86,20.99,'PG',('Deleted Scenes'),' 2006-02-15 05:03:42'),
                        (6,'AGENT TRUMAN','A Epic drama of a Feminist And a Mad Scientist who must Battel a Teacher in the candian Rocikes','2006',1,NULL,6,0.99,86,20.99,'PG',('Deleted Scenes'),' 2006-02-15 05:03:42'),
                        (7,'AIRPLANE STERRA','A Epic drama of a Feminist And a Mad Scientist who must Battel a Teacher in the candian Rocikes','2006',1,NULL,6,0.99,86,20.99,'PG',('Deleted Scenes'),' 2006-02-15 05:03:42'),
                        (8,'AIRPORT POLLOCK','A Epic drama of a Feminist And a Mad Scientist who must Battel a Teacher in the candian Rocikes','2006',1,NULL,6,0.99,86,20.99,'PG',('Deleted Scenes'),' 2006-02-15 05:03:42'),
                        (9,'ALABAMA DEVIL','A Epic drama of a Feminist And a Mad Scientist who must Battel a Teacher in the candian Rocikes','2006',1,NULL,6,0.99,86,20.99,'PG',('Deleted Scenes'),' 2006-02-15 05:03:42'),
                        (10,'ALADDIN CALENDER','A Epic drama of a Feminist And a Mad Scientist who must Battel a Teacher in the candian Rocikes','2006',1,NULL,6,0.99,86,20.99,'PG',('Deleted Scenes'),' 2006-02-15 05:03:42');
select * from film_New;


                        