INSERT INTO BRANCH (B_NAME, CITY)
VALUES
('VRCE', 'NAGPUR'),
('AJNI', 'NAGPUR'),
('KAROLBAGH', 'DELHI'),
('CHANDI', 'DELHI'),
('DHARAMPETH', 'NAGPUR'),
('M.G.ROAD', 'BANGALORE'),
('ANDHERI', 'MUMBAI'),
('VIRAR', 'MUMBAI'),
('NEHRU PLACE', 'DELHI'),
('POWAI', 'MUMBAI');
